name: Update README.md

on:
  push:	
    branches: [ master ]	
    paths: 	
      - "README.md"	

jobs:
  copyFileAndCommit:
    runs-on: ubuntu-latest
    steps:
  
    # Clone repository
    - uses: actions/checkout@v2
    
    # Copy File
    - name: Copy file
      run: |
          cp "README.md" "profile/README.md"
  
    # Commit changes
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: mousedoc
        author_email: sangyun3631@gmail.com
        message: '[Update README.md] - ${{ steps.date.outputs.date }}'
        add: 'export/score-result.md'
